name = "KB"
uuid = "e986fbee-1a5e-11e9-32b1-2b4c933ec7d8"
authors = ["kalmarek <kalmar@amu.edu.pl>", "bprzybylski <bap@amu.edu.pl>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
